### PR TITLE
Add Equally and Identity Difference

### PR DESCRIPTION
**Pull request by truecryingdev**
Hi, @snehakoshti here is my contribution about the issue on equally and identity operators.

### CODE REVIEW

**Review by snehakoshti — COMMENTED** [review]
show comparison of 
1. two primitives
2.  two objects
3. one primitives and one object

**Comment by truecryingdev** [comment]
Alright, working on it!

**Comment by truecryingdev** [comment]
It's done, @snehakoshti ready to another review

**Review by snehakoshti — COMMENTED** [review]
Can you please add ouput of each if condition in front of if statement

**Comment by truecryingdev** [comment]
Do you mean like this?
```js
if (condition) output;
```

**Comment by snehakoshti** [comment]
> Do you mean like this?
> 
> ```js
> if (condition) output;
> ```

 if (condition)    //output;

**Comment by truecryingdev** [comment]
For example, like this
```js
if(3 == '3') // true
    console.log('> 3 and "3" are the same')
```
or like this
```js
if(3 == '3') // console.log('> 3 and "3" are the same')
```

**Comment by truecryingdev** [comment]
Hi @snehakoshti can you tell me which one is correct?

**Pull request closed without merging**
